### ISSUE TITLE
Solution for ex. 3.25

### ISSUE THREAD

**Issue by xyguo** [jiangyy/NJU-TOC-Solutions#1]
这里显示不了LaTeX，我只能直接贴上来了，你把下面的文字直接拿去编译一下就可以看。应该没做错...

> \usepackage{ctex}
> \usepackage{amsmath}
> \usepackage{amssymb}
> \newcommand{\ncode}[1]{\ulcorner #1\urcorner}
> \newcommand{\eqbeta}{=_\beta}
> \newcommand{\W}{\lambda x.F(\text{App}x\text{Num}x)}
> 
> 利用第二不动点定理（定理3.42），知对于 $\forall F\in\Lambda, \exists Z\equiv W\ncode{W}$ 使得有 $F\ncode{Z}\eqbeta Z$，其中 $W\equiv\W$ .
>  故可令 $H_2\ncode{F}\eqbeta W\ncode{W}$ ，由于 $F\in\text{FV}(W)$ ，有
> \begin{equation}
> H_2\ncode{F}\eqbeta(\lambda F.W\ncode{W})F\eqbeta(\lambda F.W\ncode{W})E\ncode{F}
> \end{equation}
> 其中 $E$ 是定理3.41中构造出的枚举子。由此，取 $H_2\equiv\lambda z.(\lambda F.W\ncode{W})(Ez)$ 即可。
> % Emacs 24.4.1 (Org mode 8.2.10)

**Comment by jiangyy** [comment]
I have merged this proof into the main repository. Credits are updated. Thank you.
